### ISSUE TITLE
Upcoming meetings of a committee should be arranged by dates (descending or ascending)

### ISSUE THREAD

**Issue by AnatKatz** [hasadna/Open-Knesset#438]
### Steps:
1. Go to a committee page such as:
https://oknesset.org/committee/25/
https://oknesset.org/committee/6/
https://oknesset.org/committee/7/
2. See **ישיבות קרובות** section

### Expected result:
1. All meetings will be shown once
2. Meetings will have some kind of order

### Actual
1. Some of the meetings are shown twice
2. No order

![2](https://cloud.githubusercontent.com/assets/11028530/11784096/3d2f6b98-a283-11e5-8f49-3a0f5a7654df.png)
![1](https://cloud.githubusercontent.com/assets/11028530/11784097/3d4b90fc-a283-11e5-930b-92bf800409cd.png)

**Comment by alonisser** [comment]
@AnatKatz @OriHoch This issue is actually two different issues. and should be seperated
1. Order, I fixed easily (also still baffled why front end django templates disregard backend ordering, not a fan of django templating anyhow)

2. Double/triple existing meetings, which is a scraper issue, which  might be tough to fix, I suspect there are "small" differences between the wording of the meeting subject so it becomes another meeting, working around this would involve heuristics and might be painful. Please separate this issue to a different issue

**Comment by OriHoch** [comment]
thanks, the duplicated meetings problem hopefully was solved once we changed to use the knesset api directly, but I opened #528 to check again.

**Comment by OriHoch** [comment]
@alonisser  - looks like it's not fixed, this is after deployment of v3.0.0:
![image](https://cloud.githubusercontent.com/assets/1198854/13032798/b46f2fe8-d309-11e5-8472-1c01ba753ad1.png)

**Comment by alonisser** [comment]
Yap, I need to look at the db to find out what's happening.. and recreate this with a test.. can't recreate this locally
