### ISSUE TITLE
Bug: Graphic display under comparison of MKs 

### ISSUE THREAD

**Issue by Racvar** [hasadna/Open-Knesset#567]
I'm not sure what we're supposed to see under this tab, but in any event its currently not functioning (claims to load data, but doesn't seem to actually do anything). 

Printscreen attached. 
![image](https://cloud.githubusercontent.com/assets/16467715/13260873/2f1136de-da66-11e5-809b-5de17a80bac6.png)

**Comment by alonisser** [comment]
@OriHoch I checked and this leads to a dead link in the old non existing api, the new api doesn't support the data needed here so I guess for now resolving should be hiding the tab. agreed?

**Comment by OriHoch** [comment]
@alonisser yes
feature switching would have been useful here as well..

**Comment by OriHoch** [comment]
1. if the show_member_graph flag is enabled this page raises an error: https://oknesset.org/member/by/abc/
2. regardless of the flag, this page raises an error: https://oknesset.org/member/by/graph/

**Comment by alonisser** [comment]
@OriHoch I pushed a fix

**Comment by OriHoch** [comment]
the error is not raised, but I switched the flag off and the link to graph display is still shown

https://oknesset.org/member/by/abc/?cache_buster=osijd9812j3jr

**Comment by alonisser** [comment]
I'll check



Twitter:@alonisser <https://twitter.com/alonisser>
LinkedIn Profile <http://www.linkedin.com/in/alonisser>
Facebook <https://www.facebook.com/alonisser>
*Tech blog:*4p-tech.co.il/blog
*Personal Blog:*degeladom.wordpress.com
Tel:972-54-6734469

**Comment by alonisser** [comment]
@OriHoch Can't reproduce this, I believe this was a caching issue on django view side (and I see no reason that using cache_buster in the url would invalidate it) since cache is explictly called and set there for 5 hours.

Now It's gone.. using the cache like this is going to hurt us with feature toggles , so we need to rethink our caching approach

**Comment by OriHoch** [comment]
cool thanks, in the past the cache_buster param helped me, I guess it only works for one kind of cache..

we should add cache busting on deploy
