### ISSUE TITLE
Missing committee protocols in various committees

### ISSUE THREAD

**Issue by morchickit** [hasadna/Open-Knesset#630]
The education committee is missing a lot of protocols that are published on the Knesset website. 
Here is the Knesset protocols:
![screen shot 2016-03-20 at 18 49 52](https://cloud.githubusercontent.com/assets/3273659/13906378/bd371058-eecc-11e5-8047-87b9e5da0d69.png)

And here are open Knesset: 
![screen shot 2016-03-20 at 18 50 03](https://cloud.githubusercontent.com/assets/3273659/13906388/d738c8f2-eecc-11e5-8f13-c3022b187bff.png)

I could not find any kind of rule why this is happening. 
@OriHoch - can you have a look?

**Comment by morchickit** [comment]
חסרים פרוטוקולים גם לועדת השקיפות...

**Comment by morchickit** [comment]
חסרים עכשיו גם בועדת הכספים, ואני זוכרת שהיו שם יותר, יכול להיות שהם פשוט נעלמו מהתצוגה של הועדה?

**Comment by OriHoch** [comment]
I found the problem, fixing it now

**Comment by OriHoch** [comment]
fixed, the problem was that we scraped meeting from last 5 days, assuming the date refers to meeting update date, but actually it refers to date the meeting occured. meetings might take a few weeks to get a protocol - so we missed a lot of meetings.. I increased it to 100 days, and ran it manually, everything looks fine now, please test..

**Comment by morchickit** [comment]
Cool, will be tested here at #596 . 
Closing for now.

**Comment by morchickit** [comment]
@OriHoch - Protocols still missing, specifically those who are happening in the same same date - look here at the education committee at the Knesset- 
![screen shot 2016-03-28 at 18 39 19](https://cloud.githubusercontent.com/assets/3273659/14084816/9074a438-f514-11e5-8a2e-4e64b80436ac.png)

And at OKnesset- 
![screen shot 2016-03-28 at 18 39 27](https://cloud.githubusercontent.com/assets/3273659/14084836/a21fefe4-f514-11e5-82c0-ab6309e361a6.png)

**Comment by OriHoch** [comment]
fixed, @morchickit - please re-test
