### ISSUE TITLE
נתוני וועדות לא מתעדכנים

### ISSUE THREAD

**Issue by simonaho** [hasadna/Open-Knesset#843]
למשל באתר כנסת פתוחה הנתונים הכי חדשים בוועדת החינוך הם מחודש פברואר, בעוד שבאתר הכנסת יש נתוני פרוטוקולים של וועדת החינוך מסוף מאי

**Comment by OriHoch** [comment]
### reproduction
* goto: http://main.knesset.gov.il/Activity/committees/Education/Pages/CommitteeProtocols.aspx?ItemID=2019349
* click on the meeting title
![image](https://user-images.githubusercontent.com/1198854/28408942-bd3bf204-6d41-11e7-9ccf-b111323fcc08.png)
* get a url to download the protocol file: http://fs.knesset.gov.il//20/Committees/20_ptv_389223.doc
* goto open knesset site and look for the same protocol

#### expected
* should be there

#### actual
* not available
* last meeting with protocol for education committee is from february
* https://oknesset.org/committee/6/

**Comment by OriHoch** [comment]
fixed, now I'm scraping the new meetings, will update when done

**Comment by OriHoch** [comment]
done, all meetings should be updated

**Comment by shevyk** [comment]
Some protocols are still missing. e.g.
http://main.knesset.gov.il/Activity/committees/GovInfo/Pages/CommitteeProtocols.aspx
![image](https://user-images.githubusercontent.com/12704845/28452397-2dc9904e-6dfb-11e7-8a7c-77de896d6adb.png)

protocol from 27 June 2017 missing in Oknesset:
https://oknesset.org/committee/32/
![image](https://user-images.githubusercontent.com/12704845/28452440-61191000-6dfb-11e7-830c-0521a79cc02f.png)

**Comment by OriHoch** [comment]
@shevyk  I updated with a slightly older package, I updated again with latest package, looks ok now

**Comment by shevyk** [comment]
some protocols still missing, e.g.:
http://main.knesset.gov.il/Activity/Committees/Immigration/Pages/CommitteeProtocols.aspx
![image](https://user-images.githubusercontent.com/12704845/28498863-b332d8d8-6fb0-11e7-8359-239bb1b2be5b.png)

is missing from oknesset
